CREATE TABLE [dbo].[CategoriesBodyOfKnowledge]
(
    [CategoryCloudRowId] UNIQUEIDENTIFIER NOT NULL ,
    [BokCloudRowId] UNIQUEIDENTIFIER NOT NULL, 
	[Originator] UNIQUEIDENTIFIER NOT NULL, 
    [LastModifiedOffset] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(), 
    [CloudRowId] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID()
)
