CREATE TABLE [dbo].[LearningHistory]
(
	[StrategyHistoryId] INT IDENTITY (1, 1) NOT NULL , 
    [StrategyId] INT NOT NULL, 
	[BodyOfKnowledgeId] INT NOT NULL, 
    [Description] NVARCHAR(256) NOT NULL, 
    [SortRuleId] INT NULL DEFAULT 0, 
    [QuestionRandom] BIT NULL DEFAULT 0, 
    [QuestionMax] INT NULL DEFAULT 0, 
    [QuestionMin] INT NULL DEFAULT 0, 
    [ResponseRandom] BIT NULL DEFAULT 0, 
    [ResponseMax] INT NULL DEFAULT 0 , 
    [ResponseMin] INT NULL DEFAULT 0, 
    [ResponseMinCorrect] INT NULL DEFAULT 0, 
    [ResponseMaxCorrect] INT NULL DEFAULT 0, 
	[LearningRunDate] DATETIME NOT NULL DEFAULT SYSDATETIME(),
    [LastModifiedOffset] DATETIMEOFFSET NULL DEFAULT SYSDATETIMEOFFSET(), 
    [CloudRowId] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(), 
    CONSTRAINT [PK_LearningHistory] PRIMARY KEY ([StrategyId], [StrategyHistoryId]), 
)
