CREATE PROCEDURE [dbo].[DeteUserResponsesNotIn]
	@ResponseIds NVARCHAR(MAX)
AS
	BEGIN
		BEGIN TRANSACTION RESPONSE;
		BEGIN TRY
			DELETE FROM [dbo].[Responses]
			WHERE ResponseId not in (SELECT Item FROM DBO.SPLITSTRING(@ResponseIds));
		END TRY
		BEGIN CATCH

		IF @@TRANCOUNT>0
			ROLLBACK TRANSACTION RESPONSE;
		END CATCH;
		IF @@TRANCOUNT>0
			COMMIT TRANSACTION RESPONSE;
	END
RETURN 0