--CREATE LOGIN [BokWebApiUser] WITH PASSWORD = 'Ea{t{kYc9hq{edLglr{Udg{_msFT7_&#$!~<emfuqtwA3hq0'
--GO
--CREATE USER [BokWebApiUser] FROM LOGIN [BokWebApiUser]
--GO
GRANT CONNECT TO [BokWebApiUser]
GO
--ALTER USER [BokWebApiUser] WITH DEFAULT_SCHEMA=[dbo]
GO
GRANT CONNECT TO [BokWebApiUser]
GO
GRANT EXECUTE ON SCHEMA::[dbo] TO [BokWebApiUser]
GO
GRANT INSERT ON SCHEMA::[dbo] TO [BokWebApiUser]
GO
GRANT REFERENCES ON SCHEMA::[dbo] TO [BokWebApiUser]
GO
GRANT SELECT ON SCHEMA::[dbo] TO [BokWebApiUser]
GO
GRANT UPDATE ON SCHEMA::[dbo] TO [BokWebApiUser]
GO
GRANT CONNECT TO [BokWebApiUser] WITH GRANT OPTION 
GO
GRANT CONNECT TO [BokWebApiUser] WITH GRANT OPTION  AS [dbo]
GO
GRANT EXECUTE TO [BokWebApiUser] WITH GRANT OPTION 
GO
GRANT EXECUTE TO [BokWebApiUser] WITH GRANT OPTION  AS [dbo]
GO
GRANT INSERT TO [BokWebApiUser] WITH GRANT OPTION 
GO
GRANT INSERT TO [BokWebApiUser] WITH GRANT OPTION  AS [dbo]
GO
GRANT SELECT TO [BokWebApiUser] WITH GRANT OPTION 
GO
GRANT SELECT TO [BokWebApiUser] WITH GRANT OPTION  AS [dbo]
GO
GRANT UPDATE TO [BokWebApiUser] WITH GRANT OPTION 
GO
GRANT UPDATE TO [BokWebApiUser] WITH GRANT OPTION  AS [dbo]
GO